Boot from lima

diff --git a/zsh/bin/tmux-switch-client b/zsh/bin/tmux-switch-client
--- a/zsh/bin/tmux-switch-client
+++ b/zsh/bin/tmux-switch-client
@@ -2,4 +2,9 @@
 
 # asdf might need to be sourced from a zsh env so that's why this file exists.
 
+if ! type fzf-tmux > /dev/null; then
+  echo "fzf-tmux is required"
+  exit 1
+fi
+
 python3 $DOTFILES_DIRECTORY/zsh/bin/tmux-switch-client.py
